### ISSUE TITLE
Wordpress > Error

### ISSUE THREAD

**Issue by coultonshaw** [NHSLeadership/nightingale-companion#24]
Thank you for all the hard work that you’ve put into this new plugin for nightingale.

Unfortunately, from the plugin menu in WordPress, wp-admin/options-general.php?page=nightingale-companion if you click “settings” on the nightingale companion plugin, it results in the WordPress error screen: “Sorry, you are not allowed to access this page.”

**Comment by tblacker7** [comment]
Thank you - this is a typo in the link from the plugins page (has `-` instead of `_`) - will be fixed on next release ;)
