### ISSUE TITLE
Strange issue with a strange fix

### ISSUE THREAD

**Issue by ShanayaKR** [NHSLeadership/nightingale-companion#60]
Hi! Recently we have had an issue with the Companion plugin on our sites. When we create a new site, and start adding pages etc, the blocks disappear from the page. It's really weird because they appear in the editor still, but cannot be seen when you update and view the page. 

The fix we found for it was to go into the Companion settings, and untick and re-tick the top option (for styling the login page). This allows normal editing again. I'm not too sure when this issue started sorry, but I think my colleague said it was since the last update.

If you need any more info we are happy to try and provide this, but it's difficult without building another site. Steps I did every time the issue occurred:

- Install WP
- Install Nightingale, NHS blocks, Companion, and other plugins we use
- Install our Nightingale child theme
- Configure the theme colour, site identity etc using the 'customiser'
- Add a new page with blocks on it
- Publish/update the page
- view it, and there will be nothing 

I THINK this is the error it was giving (I just went back to my messages and found an error that was happening repeatedly at the same time. This error stopped after I messaged my colleague saying it was fixed, so I'm fairly certain it's the correct error). This error occurred from the moment I created the site (it was a subsite in a multisite if that makes any difference), up until I unticked the box in the Companion plugin. 

```
[11-Jul-2023 09:54:59 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_plugin_data() in /home/sitename/public_html/wp-content/plugins/nhsblocks/nhsblocks.php:268
Stack trace:
#0 /home/sitename/public_html/wp-includes/class-wp-hook.php(308): nhsblocks_register_style('')
#1 /home/sitename/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#2 /home/sitename/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /home/sitename/public_html/wp-settings.php(623): do_action('init')
#4 /home/sitename/public_html/wp-config.php(107): require_once('/home/sitenam...')
#5 /home/sitename/public_html/wp-load.php(50): require_once('/home/sitenam...')
#6 /home/sitename/public_html/wp-blog-header.php(13): require_once('/home/sitenam...')
#7 /home/sitename/public_html/index.php(17): require('/home/sitenam...')
#8 {main}
  thrown in /home/sitename/public_html/wp-content/plugins/nhsblocks/nhsblocks.php on line 268
```

**Comment by maheshmuralip** [comment]
Hello @ShanayaKR 
We have released a new version if NHS Blocks v1.3.17, and hope this issue will be fixed by that.
Many thanks.
